### ISSUE TITLE
Upgrade node to support remote relay chain setup

### ISSUE THREAD

**Issue by Curu24** [OAK-Foundation/OAK-blockchain#362]
Hello,

I tried to run Turing collator with relay-chain-rpc-url flag to specify a remote relay chain RPC to be used instead of the embedded one but the node process ignores it and starts syncing relay chain locally.

Here is the example setup: 
```
ExecStart=/usr/local/bin/polkadot \
  --name Polkadotters \
  --base-path '/var/lib/turing' \
  --execution wasm \
  --wasm-execution Compiled \
  --chain turing \
  --collator \
  --force-authoring \
  --node-key-file /home/polkadot/node_key \
  --trie-cache-size 0 \
  --relay-chain-rpc-url ws://178.170.48.153:9944 \
  ```
  
Probably updating dependencies to 0.9.32 and above should fix this https://github.com/paritytech/cumulus/pull/1585

**Comment by chrisli30** [comment]
@Curu24 Great, thanks for your feedback. Our runtime 293 is rolling out, which will include the change in polkadot you mentioned. I’ll notify you here once the feature is deployed and tested. 👍

**Comment by chrisli30** [comment]
@v9n, I’m assigning this issue to you for testing our node command after runtime 293. We can go over the process early next week.

**Comment by Curu24** [comment]
> @Curu24 Great, thanks for your feedback. Our runtime 293 is rolling out, which will include the change in polkadot you mentioned. I’ll notify you here once the feature is deployed and tested. +1

nice, thanks!

**Comment by chrisli30** [comment]
Hi @Curu24, great news that we have completed testing on this `--relay-chain-rpc-url` feature! 

The feature was introduced to polkadot in 0.9.32, and since we sync’ed polkadot code to 0.9.38 in Turing Network v1.9.0 it’s already working for the current version of collator program.

Could you give it a try and let us know if you encounter any issue? One thing to note is that in your example your node connects to a relay chain archive node using the port `9944`, while you also have the option to connect to another parachain archive node with port `9945`, provided it's accessible.

Your feedback is welcomed! 😄

**Comment by Curu24** [comment]
> 

just tested and works well, thanks :)

**Comment by chrisli30** [comment]
> > 
> 
> just tested and works well, thanks :)

Great! Thank you for your call-out, and feel free to create another issue if you have any other suggestions. 😄
